package au.edu.unimelb.cis.swen90007.itsms.database;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

/**
 * The TechGateway class provides a data-layer interface between
 * local Tech objects and database Tech User objects, including
 * methods fot creating, updating, and deleting Tech object data
 * in the connected database.
 */
public class TechGateway extends UserGateway {

    private List<TechSkillGateway> techSkills;

    private static final String updateUserTableString =
            "UPDATE APP.users SET username = ?, password = ?," +
                    " first_name = ?, last_name = ?" +
                    " WHERE id = ?";

    private static final String insertUserTableString =
            "INSERT INTO APP.users(username, password, first_name, last_name, staff_type)" +
                    " VALUES (?, ?, ?, ?, ?)";

    private static final String updateTechSkillsString =
            "UPDATE APP.tech_skills SET skill_level = ?" +
                    " WHERE tech_id = ? AND skill_id = ?";

    private static final String insertTechSkillString =
            "INSERT INTO APP.tech_skills(tech_id, skill_id, skill_level)" +
                    " VALUES (?, ?, ?)";

    public TechGateway(int id, String username, String password,
                       String firstName, String lastName) {
        super(id, username, password, firstName, lastName);
        this.techSkills = techSkills;
    }

    /**
     * Creates a new TechGateway object based on data retrieved
     * from the connected database.
     * @param rs the results from the database retrieval query.
     * @return a TechGateway with data from the provided database
     *           results.
     * @throws SQLException
     */
    public static TechGateway load(ResultSet rs) throws SQLException {
        int idArg = rs.getInt(1);
        String usernameArg = rs.getString(2);
        String passwordArg = rs.getString(3);
        String firstNameArg = rs.getString(4);
        String lastNameArg = rs.getString(5);
        // TODO: Tech skills?
        return new TechGateway(idArg, usernameArg, passwordArg, firstNameArg,
                lastNameArg);
    }

    /**
     * Attempts to update the data of the corresponding Tech User entry in
     * the connected database with the data from the TechGateway object.
     */
    public void update() {
        PreparedStatement updateStatement = null;
        try {
            updateStatement = DBConnection.prepare(updateUserTableString);
            updateStatement.setString(1, getUsername());
            updateStatement.setString(2, getPassword());
            updateStatement.setString(3, getFirstName());
            updateStatement.setString(4, getLastName());
            updateStatement.setInt(5, getId());
            updateStatement.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Attempts to insert the data of the Tech into the
     * connected database.
     * @return the new id returned by the database.
     */
    public int insert() {
        ResultSet autoGenerated = null;
        PreparedStatement insertStatement = null;
        try {
            insertStatement = DBConnection.prepare(insertUserTableString,
                    insertStatement.RETURN_GENERATED_KEYS);
            insertStatement.setString(1, getUsername());
            insertStatement.setString(2, getPassword());
            insertStatement.setString(3, getFirstName());
            insertStatement.setString(4, getLastName());
            insertStatement.setInt(5, 2);
            insertStatement.executeUpdate();

            autoGenerated = insertStatement.getGeneratedKeys();
            if (autoGenerated.next()) {
                setId(autoGenerated.getInt(1));
            }

            Registry.addUser(this);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return getId();
    }
}
